name: CI

permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/dotnet-build.yaml

  test:
    uses: ./.github/workflows/test.yaml
