name: CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/dotnet-build.yaml

  test:
    uses: ./.github/workflows/test.yaml
    needs: build
