name: test

permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests with Results Output
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults/*.trx

      - name: Publish Test Results to GitHub UI
        if: always() # run even if tests fail
        uses: dorny/test-reporter@v1
        with:
          name: xUnit Tests
          path: ./TestResults/*.trx
          reporter: dotnet-trx
